name: Push

on:
  # Only build on main branch when pushed (when PR is merged)
  push:
    branches:
      - main
  # Only build in PR on creation/update
  pull_request:

jobs:
  unit-test-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v4

      - name: Install dependencies
        run: |
          pwd
          yarn install --frozen-lockfile
        working-directory: ../app
#      - run:
#      - name: Run tests
#        run: yarn test

  unit-test-frontend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v4
      - uses: actions/cache@v2
        with:
          path: '**/app/jenkins-for-jira-ui/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test

