name: Push

on:
  # Only build on main branch when pushed (when PR is merged)
  push:
    branches:
      - main
  # Only build in PR on creation/update
  pull_request:

jobs:
  unit-test-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: app
      - name: Run tests
        run: yarn test
        working-directory: app

  unit-test-frontend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: volta-cli/action@v4

      - name: Install dependencies
        run: |
          nvm use
          yarn install --frozen-lockfile
        working-directory: app/jenkins-for-jira-ui
      - name: Run tests
        run: yarn test
        working-directory: app/jenkins-for-jira-ui

